server:
  port: 8081
  session-timeout: 60
  tomcat.max-threads: 100
  tomcat.uri-encoding: UTF-8


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-activiti?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-Name: com.mysql.cj.jdbc.Driver
    # Specify the DBMS
    jpa:
      database: MYSQL
      # Show or not log for each sql query
      show-sql: true
      # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
      hibernate:
        ddl-auto: update
        # Hibernate 4 naming strategy fully qualified name. Not supported with Hibernate 5.
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy
      # stripped before adding them to the entity manager)
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
#  activiti:
    #每次应用启动不检查Activiti数据表是否存在及版本号是否匹配，提升应用启动速度
#    database-schema-update: false
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
#    history-level: full
    #
#    check-process-definitions: false
  #设置超时时间（2秒）
  mvc:
    async:
      request-timeout: 2000

