server:
  servlet:
    context-path: /demo

spring:
  profiles:
    active: dev

rocket:
  host: 61.174.54.126
  port: 9876
topic:
  tRegion: region_topic_dev
group:
  tRegion: region_group_dev
tag:
  tRegion: region_tag_dev






